# ver: 0.9.2
# rubocop: v0.52

inherit_from:
  # - .rubocop_rspec.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  EnforcedStyle: with_first_parameter

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
  IndentationWidth: 2

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# for the following case.
#   validates :project , presence: true
#   validates :title   , presence: true
#   validates :status  , presence: true
Layout/SpaceBeforeComma:
  Enabled: false

# for the following case.
#   expect(json['title']).to    eq 'implement hoge'
#   expect(json['status']).to   eq 'todo'
#   expect(json['priority']).to eq 1
#   expect(json['point']).to    eq 1
Layout/SpaceBeforeFirstArg:
 Enabled: false

# for the following case.
#   db       = ENV['db']       || 'apollo'
#   user     = ENV['user']     || 'postgres'
#   password = ENV['password'] || ''
Layout/SpaceAroundOperators:
  Enabled: false
